---

- name: stopping kafka mirror maker processes
  ansible.builtin.include_role:
    name: serviceState
  vars:
    serviceName: "kafka-mirror-maker-{{ item }}"
    serviceState: stopped
  loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"

- name: checking port status of kafka mirror maker processes
  ansible.builtin.include_role:
    name: portCheck
  vars:
    portNumber: "{{ kafkaMirrorMakerJmxInitialPort + item }}"
    portStatus: stopped
  loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"

- name: Removing all installation files for kafka mirror maker
  ansible.builtin.command: "/bin/rm -rf {{ kafkaInstallDir }}/*kafka*"

- name: Removing data & log dirs related to installation
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "{{ kafkaInstallDir }}/kafka"
    - "{{ kafkaDataDir }}"
    - "{{ kafkaLogDir }}"
    - "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}"
    - "{{ kafkaInstallDir }}/kafka_{{ kafkaOldVersion }}-{{ kafkaOldScalaVersion }}"
    - "{{ kafkaInstallDir }}/jmxMonitor"

- name: Removing all systemd files
  ansible.builtin.command: "/bin/rm -rf /usr/lib/systemd/system/kafka-mirror-maker*.service"