---

- name: Waiting for port | {{ portNumber }} | to be | {{ portStatus }}
  ansible.builtin.wait_for:
    host: "0.0.0.0"
    port: "{{ portNumber }}"
    state: "{{ portStatus }}"
    timeout: 180
    delay: 10
