---

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  become: true
  roles:
    - java
    - common

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  become: true
  tasks:
    - name: installing latest version of kafka
      ansible.builtin.import_role:
        name: install
        tasks_from: download

    - name: configuring latest kafka version
      ansible.builtin.import_role:
        name: configure

- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Switching Kafka Version to {{ kafkaVersion }} on all nodes (Rolling fashion)
      ansible.builtin.pause:
        prompt: "press enter to confirm or ctrl-c to cancel"

- hosts: clusterNodes:clusterAddNodes
  gather_facts: false
  become: true
  serial: 1
  tasks:
    - name: switching kafka version to {{ kafkaVersion }}
      ansible.builtin.import_role:
        name: install
        tasks_from: createSymlink

    - name: restarting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: kafka
        serviceState: restarted

    - name: kafka Port Status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"
