---

- hosts: clusterNodes:clusterAddNodes:kafka-mirror-maker
  gather_facts: true
  become: true
  pre_tasks:
    - name: install gcc and python-devel ( Redhat / CentOS )
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - python3-devel
      when: ansible_distribution in ['CentOS', 'RedHat'] | list

    - name: install gcc and python-devel ( Debain / Ubuntu )
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - python3-dev
      when: ansible_distribution in ['Debian', 'Ubuntu'] | list

    - name: copy jmxquery / psutil tar files
      ansible.builtin.copy:
        src: "roles/jmxMonitor/files/{{ item }}"
        dest: "/tmp/{{ item }}"
      loop:
        - jmxquery-0.6.0.tar.gz
        - psutil-5.8.0.tar.gz

    - name: installing jmxquery / psutil with pip3
      ansible.builtin.pip:
        name: /tmp/{{ item }}
        executable: pip3
      loop:
        - jmxquery-0.6.0.tar.gz
        - psutil-5.8.0.tar.gz

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  roles:
    - jmxMonitor

- hosts: kafka-mirror-maker
  gather_facts: true
  tasks:
    - ansible.builtin.include_role:
        name: jmxMonitor
        tasks_from: kafka-mirror-maker.yml
