---

- hosts: clusterAddNodes
  gather_facts: true
  become: true
  serial: 1
  roles:
    - java
    - common
    - install
    - configure
    - service
    - crons

  post_tasks:
    - name: Starting additional nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: kafka
        serviceState: started

    - name: kafka Port Status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"
