---

- hosts: kafka-mirror-maker-remove-nodes
  gather_facts: true
  any_errors_fatal: true
  become: true
  serial: 1
  tasks:
    - ansible.builtin.include_role:
        name: decomissionNodes
        tasks_from: kafka-mirror-maker.yml
