---

- hosts: clusterNodes[2]
  gather_facts: true
  tasks:
    - name: copy kafka-python package
      copy:
        src: "roles/jmxMonitor/files/{{ item }}"
        dest: "/tmp/{{ item }}"
      loop:
        - kafka_python-2.0.1-py2.py3-none-any.whl

    - name: installing kafka_python with pip3
      pip:
        name: /tmp/{{ item }}
        executable: pip3
      loop:
        - kafka_python-2.0.1-py2.py3-none-any.whl

    - include_role:
        name: jmxMonitor
        tasks_from: kafka-consumer-group-metric.yml
