---

- hosts: clusterNodes
  gather_facts: true
  become: true
  roles:
    - java
    - common
    - install
    - configure
    - service
    - crons

- hosts: clusterNodes
  gather_facts: false
  serial: 1
  tasks:
    - name: starting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: kafka
        serviceState: started

    - name: kafka Port Status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"
