---

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  become: true
  serial: 1
  tasks:
    - ansible.builtin.include_role:
        name: configure
        tasks_from: dynamicConfigs
      vars:
        - kafkaConfigFile: log4j.properties

    - name: restarting all nodes
      ansible.builtin.import_role:
        name: serviceState
      vars:
        serviceName: kafka
        serviceState: restarted
      when: configStatus.changed

    - name: kafka port status
      ansible.builtin.include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"
      when: configStatus.changed
