---

- hosts: clusterNodes:clusterAddNodes
  gather_facts: false
  serial: 1
  tasks:
    - name: current kafka version
      set_fact:
        kafkaCurrentVersion: "kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}"
        kafkaRemoveVersion: "kafka_{{ kafkaOldScalaVersion }}-{{ kafkaOldVersion }}"
  
    - name: removing old kafka config files | {{ kafkaInstallDir }}/kafka_{{ kafkaOldScalaVersion }}-{{ kafkaOldVersion }}
      file:
        path: "{{ kafkaInstallDir }}/kafka_{{ kafkaOldScalaVersion }}-{{ kafkaOldVersion }}"
        state: absent
      when:
        - kafkaOldVersion is defined
        - kafkaOldScalaVersion is defined
        - kafkaRemoveVersion is version(kafkaCurrentVersion, '!=')