---

- hosts: kafka-mirror-maker
  gather_facts: true
  become: true
  serial: 1
  tasks:
    - ansible.builtin.include_role:
        name: serviceState
      vars:
        serviceName: "kafka-mirror-maker-{{ item }}"
        serviceState: restarted
      loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"

    - ansible.builtin.include_role:
        name: portCheck
      vars:
        portNumber: "{{ kafkaMirrorMakerJmxInitialPort + item }}"
        portStatus: started
      loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"
