---

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  serial: 1
  tasks:
    - name: including restart tasks
      import_role:
        name: serviceState
      vars:
        serviceName: kafka
        serviceState: restarted

    - name: kafka port status
      include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ kafkaPort }}"
        - "{{ kafkaJmxPort }}"