---

- hosts: clusterNodes:clusterAddNodes:kafka-mirror-maker
  gather_facts: true
  become: true
  tasks:
    - name: install gcc and python-devel ( Redhat / CentOS )
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - python3-devel
      when: ansible_distribution in ['CentOS', 'RedHat'] | list

    - name: install gcc and python-devel ( Debain / Ubuntu )
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - python3-dev
      when: ansible_distribution in ['Debian', 'Ubuntu'] | list

    - name: copy python requirements
      ansible.builtin.copy:
        src: "roles/jmxMonitor/files/requirements.txt"
        dest: "/tmp/requirements.txt"

    - name: installing kafka_python with pip3
      ansible.builtin.pip:
        requirements: "/tmp/requirements.txt"
        executable: pip3

- hosts: clusterNodes:clusterAddNodes
  gather_facts: true
  roles:
    - jmxMonitor

- hosts: kafka-mirror-maker
  gather_facts: true
  tasks:
    - ansible.builtin.include_role:
        name: jmxMonitor
        tasks_from: kafka-mirror-maker.yml

- hosts: clusterNodes:clusterAddNodes:kafka-mirror-maker
  gather_facts: true
  become: true
  tasks:
    - name: clean temp files
      ansible.builtin.file:
        path: "/tmp/requirements.txt"
        state: absent