---

- hosts: kafka-manager
  gather_facts: true
  become: true
  pre_tasks:
    - ansible.builtin.include_role:
        name: common
        tasks_from: createUser.yml
  roles:
    - java
    - kafka-manager
