---

# Notes:
# New version of integration can be downloaded from below link
# Redhat / CentOS: https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64
# Ubuntu / Debain: https://download.newrelic.com/infrastructure_agent/linux/apt/pool/main/n/

# NewRelic Integration should be installed on all broker nodes
- hosts: clusterNodes:clusterAddNodes
  become: true
  gather_facts: true
  pre_tasks:
    - name: checking newrelic infra agent status ( Redhat / CentOS )
      ansible.builtin.shell: "set -o pipefail && rpm -qa | grep newrelic-infra"
      when: ansible_distribution in ['CentOS', 'RedHat'] | list
      register: isNewRelicInfraInstalledYum

    - name: checking newrelic infra agent status ( Ubuntu / Debain )
      ansible.builtin.shell: "set -o pipefail && apt list --installed | grep -i newrelic-infra"
      when: ansible_distribution in ['Debian', 'Ubuntu'] | list
      register: isNewRelicInfraInstalledApt

  roles:
    - role: nri-kafka
      when:
        - isNewRelicInfraInstalledYum != '' or isNewRelicInfraInstalledApt != ''
        - isNewRelicInfraInstalledYum is not skipped or isNewRelicInfraInstalledApt is not skipped

- hosts: kafka-mirror-maker
  become: true
  gather_facts: true
  pre_tasks:
    - name: checking newrelic infra agent status ( Redhat / CentOS )
      ansible.builtin.shell: "set -o pipefail && rpm -qa | grep newrelic-infra"
      when: ansible_distribution in ['CentOS', 'RedHat'] | list
      register: isNewRelicInfraInstalledYum

    - name: checking newrelic infra agent status ( Ubuntu / Debain )
      ansible.builtin.shell: "set -o pipefail && apt list --installed | grep -i newrelic-infra"
      when: ansible_distribution in ['Debian', 'Ubuntu'] | list
      register: isNewRelicInfraInstalledApt

  tasks:
    - ansible.builtin.include_role:
        name: nri-kafka
        tasks_from: kafka-mirror-maker.yml
      when:
        - isNewRelicInfraInstalledYum != '' or isNewRelicInfraInstalledApt != ''
        - isNewRelicInfraInstalledYum is not skipped or isNewRelicInfraInstalledApt is not skipped
