---
- name: Setting java update true if required
  set_fact:
    javaUpdateState: latest
  when: updateJava

- name: Install Openjdk | {{ javaVersion }} | RedHat | if java version is less than 9
  yum:
    name: "{{ item }}"
    state: "{{ javaUpdateState | default('present') }}"
    update_cache: true
  loop:
    - "java-1.{{ javaVersion }}.0-openjdk"
    - "java-1.{{ javaVersion }}.0-openjdk-devel"
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
    - javaVersion | int < 9

# TODO: Java 9 & 10 packages are not avilable
- name: Install Openjdk | {{ javaVersion }} | RedHat | if java version is greater than 9
  yum:
    name: "{{ item }}"
    state: "{{ javaUpdateState | default('present') }}"
    update_cache: true
  loop:
    - "java-{{ javaVersion }}-openjdk"
    - "java-{{ javaVersion }}-openjdk-devel"
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
    - javaVersion | int >= 9

- name: Install OpenJdk | {{ javaVersion }} | Debian/Ubuntu
  apt:
    name: "{{ item }}"
    state: "{{ javaUpdateState | default('present') }}"
    update_cache: true
  loop:
    - "openjdk-{{ javaVersion }}-jdk-headless"
    - "openjdk-{{ javaVersion }}-jdk"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
