---
- name: Creating kafka configurations | {{ kafkaConfigFile }}
  ansible.builtin.template:
    src: "{{ kafkaConfigFile }}"
    dest: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}/config/{{ kafkaConfigFile }}"
  register: configStatus
