---
- name: Creating kafka configurations | {{ kafkaConfigFile }}
  template:
    src: "{{ kafkaConfigFile }}"
    dest: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}/config/{{ kafkaConfigFile }}"
  register: configStatus