---
- ansible.builtin.include_tasks: jvmSettings.yml

- name: Creating kafka configurations
  ansible.builtin.include_role:
      name: configure
      tasks_from: dynamicConfigs.yml
  vars:
    - kafkaConfigFile: "{{ item }}"
  loop:
    - kafka-broker.properties
    - log4j.properties
