---

- name: Install Common Utils
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - net-tools
    - tar
    - unzip
    - wget

- name: install python3* packages and dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - python3
    - python3-pip
    - python3-devel
    - gcc
