---

- name: Installing common utils
  ansible.builtin.include_tasks: commonUtils.yml

- name: Create user and group
  ansible.builtin.include_tasks: createUser.yml

- name: Create kafka dir structure
  ansible.builtin.include_tasks: createDirStructure.yml

- name: System tuning tasks
  ansible.builtin.include_tasks: systemTuning.yml

- name: Disable firewall
  ansible.builtin.include_tasks: disableFirewall.yml
  ignore_errors: true
  when: not useSystemFirewall
