---

- include_tasks: packages.yml

- name: copying newrelic integration config file
  template:
    src: "{{ item }}"
    dest: "/etc/newrelic-infra/integrations.d/{{ item }}"
  loop:
    - jmx-config.yml
    - kafka-jvm-metrics.yml
    - kafka-metrics.yml

- name: restarting newrelic infra agent
  service:
    name: newrelic-infra
    state: restarted