---

- name: settings names for newrelic jmx monitoring rpms
  set_fact:
    newRelicCliJmxRpmName: nrjmx-1.3.0-1.x86_64.rpm
    newRelicJmxRpmName: nri-jmx-2.1.0-1.x86_64.rpm

- name: copying newrelic integration rpms
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - "{{ newRelicCliJmxRpmName }}"
    - "{{ newRelicJmxRpmName }}"

- name: installing newrelic integration on host
  yum:
    name: "/tmp/{{ item }}"
    state: present
  loop:
    - "{{ newRelicCliJmxRpmName }}"
    - "{{ newRelicJmxRpmName }}"

- name: copying newrelic integration config file
  template:
    src: "{{ item }}"
    dest: "/etc/newrelic-infra/integrations.d/{{ item }}"
  loop:
    - jmx-config.yml
    - kafka-jvm-metrics.yml
    - kafka-metrics.yml

- name: restarting newrelic infra agent
  service:
    name: newrelic-infra
    state: restarted

- name: removing newrelic infra rpm from server
  file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - "{{ newRelicCliJmxRpmName }}"
    - "{{ newRelicJmxRpmName }}"