---

- ansible.builtin.include_tasks: packages.yml

- name: copying newrelic integration config file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/newrelic-infra/integrations.d/{{ item }}"
  loop:
    - jmx-config.yml
    - kafka-jvm-metrics.yml
    - kafka-metrics.yml

- name: restarting newrelic infra agent
  ansible.builtin.service:
    name: newrelic-infra
    state: restarted
