---

- name: creating folder for jmx monitor
  ansible.builtin.file:
    path: "{{ kafkaInstallDir }}/jmxMonitor"
    state: directory
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"

- name: copying script and input files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kafkaInstallDir }}/jmxMonitor/{{ item }}"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
  loop:
    - kafka-jmx-metric-collector-mm.py
    - kafka-mirror-input.txt

- name: kafka mirror metric collector cron
  ansible.builtin.cron:
    name: "kafka mirror metric collector cron task {{ item }}"
    minute: "*"
    hour: "*"
    weekday: "*"
    user: "{{ kafkaUser }}"
    job: 'python3 {{ kafkaInstallDir }}/jmxMonitor/kafka-jmx-metric-collector-mm.py {{ ansible_fqdn }} {{ kafkaMirrorMakerJmxInitialPort + item }} {{ kafkaInstallDir }}/jmxMonitor/kafka-mirror-input.txt {{ kafkaLogDir }}/Kafka-Mirror-Maker-Process-{{ item }}- {{ kafkaClusterName }} Kafka-Mirror-Maker-Process-{{ item }} \;'
  loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"
