- name: creating folder for jmx monitor
  ansible.builtin.file:
    path: "{{ kafkaInstallDir }}/jmxMonitor"
    state: directory
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"

- name: copying script and input files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kafkaInstallDir }}/jmxMonitor/{{ item }}"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
  loop:
    - kafka-consumer-group-metric.py
    - kafka-consumer-group-metric-input.txt

- name: creating kafka consumer group metric collector cron
  ansible.builtin.cron:
    name: "kafka consumer group metric collector cron task"
    minute: "*"
    hour: "*"
    weekday: "*"
    user: "{{ kafkaUser }}"
    job: 'python3 {{ kafkaInstallDir }}/jmxMonitor/kafka-consumer-group-metric.py {{ kafkaInstallDir }}/jmxMonitor/kafka-consumer-group-metric-input.txt {{ kafkaLogDir }}/ {{ kafkaClusterName }}'
